name: Update data on NFDI4Health via API

on:
  workflow_dispatch:
#  push:
#    paths:
#      - 'Metadaten/nfdi4health.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.0.2
      
      - name: Read nfdi4health.json content
        run: |
            echo "NFDI4HEALTH_DATA=`cat ./path/to/package.json`" >> $GITHUB_ENV

      - name: POST nfdi4health.json
        uses: fjogeleit/http-request-action@v1
          with:
            url: 'https://csh.nfdi4health.de/mdr/studyhub_resources'
            method: 'POST'
            customHeaders: '{"Content-Type": "application/json", "Accept": "application/json", "Authorization": "Token ${{ secrets.NFDI4HEALTH_TOKEN }}"}'
            data: env.NFDI4HEALTH_DATA
