# This is a basic workflow to help you get started with Actions

name: Create Release on push

# Controls when the action will run. 
on:
 push:
  tags:
    - '[0-9][0-9][0-9][0-9]-[0-1][0-9]-[0-3][0-9]'

env:
  zenodo_deposition_id: 1091776
  zenodo_server: 'https://sandbox.zenodo.org'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          lfs: 'true'
        #  fetch-depth: 2
      
      - name: Create new deposition draft on zenodo
        uses: kykrueger/zenodo-new-version@v1.0.2
        with:
         whitelist_replace_doi: .github/workflows/.zenodo_whitelist_replace_doi
         zenodo_deposition_id: ${{ env.zenodo_deposition_id }}
         zenodo_server: ${{ env.zenodo_server }}
         zenodo_token: ${{ secrets.ZENODO_TOKEN }} 
         
      - name: CreateWorkingDir
        run: mkdir md2pdf & cp Readme*.md md2pdf/ 
        
      # Build pdfs  
      - name: Create Readme.pdf
        uses: baileyjm02/markdown-to-pdf@v1.2.0
        with:
          input_dir: md2pdf/
          output_dir: md2pdf/
          image_import: /.github/pictures   #Uncomment if u use imgges in your Readme.md
          images_dir: /.github/pictures     #Uncomment if u use imgges in your Readme.md
          build_html: false
      
      # Renames Readme.pdf to 'Dokumentation <reponame>.pdf'
      - name: Rename Readme.pdf
        run: mv md2pdf/Readme.pdf "[Dokumentation]_$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' ).pdf"
      - name: Rename Readme_en.pdf
        run: |
          if [ -f md2pdf/Readme_en.pdf ]; then
             mv md2pdf/Readme_en.pdf "[Documentation]_$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' ).pdf"
          fi  
          
      - name: Clean Working Directory
        run: rm -rf md2pdf .tmp_zenodo_deposition.json
        
      - name: Add and Commit Changes 
        uses: EndBug/add-and-commit@v9
        with:
        #  push: origin HEAD:master
          pull: true
          push: 'origin HEAD:master'
          message: 'DOI replaced in documentation.'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Datenstand ${{ github.ref }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  
