# This is a basic workflow to help you get started with Actions

name: Publish Website to Github

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_dispatch:
  release:
  # push:
    # branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Pull website code
        # run: git clone https://github.com/whoohoo86/gh-open-data-page.git
        uses: actions/checkout@v2
        with:
          repository: 'whoohoo86/gh-open-data-page'
          
      - name: Echo some content
        run : "ls -la $GITHUB_WORKSPACE"
        
      - name: Create datasource.json
        uses: ./
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14.x

      # Runs a set of commands using the runners shell
      - name: Prepare and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run ng -- deploy --base-href=/dummyDataRepo/ --name="EckelmannF" --email=eckelmannf@rki.de
