name: Upload data to NFDI4Health API

on:
  workflow_dispatch:
  push:
    paths:
      - 'Metadaten/**.nfdi4health.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Read id from 'Metadaten/**.nfdi4health.json'
        run: |
          echo $github
          echo $GITHUB_EVENT_PATH
          echo "`jq '.data.id"' $GITHUB_EVENT_PATH`"
